"""
Bedrock AgentCore Runtime invoker for the voice pipeline.

The browser cannot call the AgentCore data-plane directly (it emits no CORS
headers), so WebRTC signaling is proxied server-to-server: the control-plane
router validates the caller (via the host's ``authorize`` hook) and then calls
``invoke_agent_runtime`` here. Auth to the runtime is IAM/SigV4 via the API
host's execution role (no explicit credentials) — grant it with
``runtime.grantInvoke(apiLambda)`` in infra/voice-runtime.ts.

Passing ``runtimeSessionId`` pins every signaling round-trip for one
conversation to the same runtime container (session affinity) — required
because peer-connection state lives in that container's memory. The two ids are
distinct: the host ``session_id`` is the pointer the runtime's context provider
re-fetches by, and ``runtime_session_id`` is the AgentCore affinity key
(regenerated by the frontend on a cold-start ICE failure, same ``session_id``).
"""

import asyncio
import json
import logging
from typing import Optional

from ..config import settings
from ..errors import UpstreamServiceError
from .invoker import Invoker

logger = logging.getLogger(__name__)

# Reused across warm invocations, created lazily on first use (a module-scope
# client would require AWS credentials/region at import, breaking test and
# non-AWS imports). Region is resolved automatically in-Lambda;
# settings.aws_region is mainly for local runs.
_agentcore_client = None


def _get_client():
    global _agentcore_client
    if _agentcore_client is None:
        import boto3

        _agentcore_client = boto3.client(
            "bedrock-agentcore", region_name=settings.aws_region
        )
    return _agentcore_client


class AgentCoreInvoker(Invoker):
    """
    Invoker backed by boto3 ``invoke_agent_runtime``.

    boto3 is synchronous, so every call is pushed off the event loop with
    ``asyncio.to_thread`` — sync boto3 in an async route blocks the loop under
    a local uvicorn (in-Lambda it merely serializes, which Mangum does anyway).

    Args:
        runtime_arn: AgentCore Runtime ARN; defaults to
            ``settings.voice_runtime_arn``.
    """

    def __init__(self, runtime_arn: Optional[str] = None):
        self._runtime_arn = runtime_arn

    async def signal(
        self,
        session_id: str,
        runtime_session_id: str,
        sdp: str,
        type: str = "offer",
    ) -> dict:
        """
        Proxy one WebRTC signaling round-trip to the voice runtime and return
        its SDP answer.

        The invoke payload follows the runtime's pointer + re-fetch contract:
        it carries only ``{session_id, sdp, type}`` — the runtime resolves
        everything else through its registered context provider, and no
        ``action`` key means the entrypoint's default ``"signal"`` branch runs.
        """
        return await self._invoke(
            runtime_session_id,
            {"session_id": session_id, "sdp": sdp, "type": type},
        )

    async def end(self, session_id: str, runtime_session_id: str) -> dict:
        """
        Ask the runtime (same container, via the affinity key) to tear down
        the session's pipeline. The entrypoint dispatches on ``action: "end"``.
        """
        return await self._invoke(
            runtime_session_id,
            {"session_id": session_id, "action": "end"},
        )

    async def _invoke(self, runtime_session_id: str, payload: dict) -> dict:
        return await asyncio.to_thread(self._invoke_sync, runtime_session_id, payload)

    def _invoke_sync(self, runtime_session_id: str, payload: dict) -> dict:
        import botocore.exceptions

        session_id = payload.get("session_id")
        try:
            response = _get_client().invoke_agent_runtime(
                agentRuntimeArn=self._runtime_arn or settings.voice_runtime_arn,
                runtimeSessionId=runtime_session_id,
                payload=json.dumps(payload).encode("utf-8"),
            )
        except (
            botocore.exceptions.BotoCoreError,
            botocore.exceptions.ClientError,
        ) as e:
            logger.exception(
                "Voice runtime invoke failed for session %s (runtime_session_id=%s)",
                session_id,
                runtime_session_id,
            )
            raise UpstreamServiceError(
                message="The voice service could not be reached.",
                details={"error": str(e)},
            )
        logger.info(
            "Invoked voice runtime for session %s (runtime_session_id=%s)",
            session_id,
            runtime_session_id,
        )

        # The response payload is a streaming body of JSON bytes.
        body = response["response"].read()
        answer = json.loads(body)
        # The runtime returns {"error": ...} instead of a result when it cannot
        # comply (e.g. offer-handling timeout). Surface it as a 502 so the
        # browser gets a CORS-bearing error instead of a KeyError-driven 500.
        if isinstance(answer, dict) and "error" in answer:
            raise UpstreamServiceError(
                message="The voice service could not negotiate the connection.",
                details={"error": answer["error"]},
            )
        return answer
