"""
Request/response schemas for the voice control-plane router.

The wire contract between the frontend client (web/src/voice/voiceApi.ts) and
the three signaling endpoints. Field names must stay in sync with the frontend
types (web/src/voice/webrtc.types.ts).
"""

from typing import List, Optional

from pydantic import BaseModel

from ..types import IceServerConfig, TranscriptMessage

__all__ = [
    "IceServerConfig",
    "SessionStartResponse",
    "SessionEndRequest",
    "SessionEndResponse",
    "SignalRequest",
    "SignalResponse",
]


class SessionStartResponse(BaseModel):
    """
    Response when starting a voice session.

    Returns the AgentCore affinity key the frontend pins all signaling to (via
    the `/signal` proxy), the host session id, and the browser's own KVS
    managed-TURN `ice_servers`. The browser MUST build its RTCPeerConnection with
    these (relay-only): in WebRTC each peer needs its own TURN allocation, so
    without them the browser gathers only private host candidates and the
    runtime's relay CHANNEL_BIND is rejected ("403 Forbidden IP") → ICE stalls.
    On a cold-start ICE failure the frontend retries with a fresh
    `runtime_session_id`, same `session_id`.

    `ice_servers` is empty in local mode (`BRIDGE_LOCAL=1`): both peers are on
    loopback, so the browser connects on host candidates with no TURN at all.
    """

    runtime_session_id: str
    session_id: str
    ice_servers: List[IceServerConfig] = []


class SessionEndRequest(BaseModel):
    """
    Optional body for the end endpoint.

    The control plane is stateless, so it cannot know the AgentCore affinity
    key on its own — the browser holds it. When `runtime_session_id` is
    present, the router best-effort invokes the runtime's teardown
    (`action: "end"`) before the host's `on_end` hook; when absent (or no
    body at all), teardown is skipped and the pipeline idle timeout is the
    backstop.
    """

    runtime_session_id: Optional[str] = None


class SessionEndResponse(BaseModel):
    """Response when ending a voice session.

    ``transcript`` is whatever the host's ``on_end`` hook returns — typically
    the server-side transcript re-read AFTER any status flip (the runtime
    writes turns live, so an earlier snapshot can miss turns).
    """

    message: str
    transcript: List[TranscriptMessage] = []


class SignalRequest(BaseModel):
    """
    WebRTC signaling request proxied to the voice runtime.

    `runtime_session_id` is the affinity key returned by the start endpoint
    (regenerated by the frontend on a cold-start retry); `sdp`/`type` are the
    browser's non-trickle offer.
    """

    runtime_session_id: str
    sdp: str
    type: str = "offer"


class SignalResponse(BaseModel):
    """The voice runtime's SDP answer, relayed back to the browser."""

    sdp: str
    type: str = "answer"
