"""
Bedrock AgentCore Runtime invoke helper for the voice pipeline.

The browser cannot call the AgentCore data-plane directly (it emits no CORS
headers), so WebRTC signaling is proxied server-to-server: the control-plane
router validates the caller (via the host's ``authorize`` hook) and then calls
``invoke_agent_runtime`` here. Auth to the runtime is IAM/SigV4 via the API
host's execution role (no explicit credentials) — grant it with
``runtime.grantInvoke(apiLambda)`` in infra/voice-runtime.ts.

Passing ``runtimeSessionId`` pins every signaling round-trip for one
conversation to the same runtime container (session affinity) — required
because peer-connection state lives in that container's memory. The two ids are
distinct: the host ``session_id`` is the pointer the runtime's context provider
re-fetches by, and ``runtime_session_id`` is the AgentCore affinity key
(regenerated by the frontend on a cold-start ICE failure, same ``session_id``).
"""

import json
import logging
from typing import Optional

from ..config import settings
from ..errors import UpstreamServiceError

logger = logging.getLogger(__name__)

# Reused across warm invocations, created lazily on first use (a module-scope
# client would require AWS credentials/region at import, breaking test and
# non-AWS imports). Region is resolved automatically in-Lambda;
# settings.aws_region is mainly for local runs.
_agentcore_client = None


def _get_client():
    global _agentcore_client
    if _agentcore_client is None:
        import boto3

        _agentcore_client = boto3.client(
            "bedrock-agentcore", region_name=settings.aws_region
        )
    return _agentcore_client


def invoke_voice_runtime(
    session_id: str,
    runtime_session_id: str,
    sdp: str,
    type: str,
    runtime_arn: Optional[str] = None,
) -> dict:
    """
    Proxy one WebRTC signaling round-trip to the voice runtime and return its
    SDP answer.

    The invoke payload follows the runtime's pointer + re-fetch contract: it
    carries only ``{session_id, sdp, type}`` — the runtime resolves everything
    else through its registered context provider. ``runtimeSessionId`` pins the
    call to one container for the life of the conversation.

    Args:
        session_id: Session id (the runtime's only context pointer).
        runtime_session_id: AgentCore affinity key for this connection attempt.
        sdp: The browser's non-trickle SDP offer.
        type: The SDP type (e.g. ``"offer"``).
        runtime_arn: AgentCore Runtime ARN; defaults to
            ``settings.voice_runtime_arn``.

    Returns:
        dict: The runtime's SDP answer, e.g. ``{"sdp": ..., "type": "answer"}``.

    Raises:
        UpstreamServiceError: If the invoke fails. Surfaced as a domain
            exception (502) so the response carries CORS headers — a bare botocore
            error would escape the CORS middleware as a CORS-less 500 that the
            browser blocks and reports as a meaningless "Network Error".
    """
    import botocore.exceptions

    try:
        response = _get_client().invoke_agent_runtime(
            agentRuntimeArn=runtime_arn or settings.voice_runtime_arn,
            runtimeSessionId=runtime_session_id,
            payload=json.dumps(
                {"session_id": session_id, "sdp": sdp, "type": type}
            ).encode("utf-8"),
        )
    except (botocore.exceptions.BotoCoreError, botocore.exceptions.ClientError) as e:
        logger.exception(
            "Voice runtime invoke failed for session %s (runtime_session_id=%s)",
            session_id,
            runtime_session_id,
        )
        raise UpstreamServiceError(
            message="The voice service could not be reached.",
            details={"error": str(e)},
        )
    logger.info(
        "Invoked voice runtime for session %s (runtime_session_id=%s)",
        session_id,
        runtime_session_id,
    )

    # The response payload is a streaming body of JSON bytes.
    body = response["response"].read()
    answer = json.loads(body)
    # The runtime returns {"error": ...} instead of an SDP answer when it cannot
    # negotiate (e.g. offer-handling timeout). Surface it as a 502 so the browser
    # gets a CORS-bearing error instead of a KeyError-driven 500.
    if isinstance(answer, dict) and "error" in answer:
        raise UpstreamServiceError(
            message="The voice service could not negotiate the connection.",
            details={"error": answer["error"]},
        )
    return answer
